# Generated by Django 5.1.5 on 2025-02-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
